chore: fix workflow

diff --git a/.github/workflows/check-pr-to-main.yaml b/.github/workflows/check-pr-to-main.yaml
--- a/.github/workflows/check-pr-to-main.yaml
+++ b/.github/workflows/check-pr-to-main.yaml
@@ -1,17 +1,18 @@
-name: check-pull-request-to-main
+name: Check Pull Request to main
 run-name: Checking Pull Request to main branch
 on:
-	pull_request:
-		types: [opened, reopened]
-	branches:
-		- "main"
+  pull_request:
+    types:
+      - opened
+      - reopened
+    branches:
+      - "main"
 jobs:
-	check-pull-request-to-main:
-		runs-on: ubuntu-latest
-		steps:
-			-name: Checking Pull Request
-				if: github.base_ref == 'main' && github.head_ref != 'develop'
-				- uses: actions/github-script@v7
-						with:
-							script: |
-								core.setFailed('Pull Request failed. You can only merge to main from develop.')
+  check-pull-request-to-main:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checking Pull Request
+        if: github.base_ref == 'main' && github.head_ref != 'develop'
+        run: |
+          echo "ERROR: You can only merge to main from dev."
+          exit 1
